server:
  grpc:
    address: localhost:8443
    certFilename: test-certs/server-cert.pem
    keyFilename: test-certs/server-key.pem
    clientCACert: test-certs/ca-cert.pem
    reflectionApiEnabled: true
